name: Build and push docker image with TEMP-suffix
on: workflow_dispatch
jobs:
  build_and_push:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: 'Backend: Build maven artifacts'
        run: mvn -f ./api/pom.xml -B package
      - name: 'Frontend: Install dependencies'
        run: npm ci --legacy-peer-deps --prefix web-app
      - name: 'Frontend: Build assets'
        run: npm run build --prefix web-app
      - name: Build and push
        uses: nais/docker-build-push@v2
        with:
          team: poao
          image-suffix: 'TEMP'
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
